base: 'http://devega.local/'
baseVariants:
  -
    base: 'http://devega.local/'
    condition: 'applicationContext == "Development"'
errorHandling:
  -
    errorCode: 404
    errorHandler: Page
    errorContentSource: 't3://page?uid=89'
languages:
  -
    title: German
    enabled: true
    base: 'http://devega.local/'
    typo3Language: de
    locale: de_DE.UTF-8
    iso-639-1: de
    websiteTitle: ''
    navigationTitle: German
    hreflang: de-DE
    direction: ltr
    flag: de
    languageId: 0
rootPageId: 1
routeEnhancers:
  PageTypeSuffix:
    type: PageType
    map:
      /: 0
      sitemap.xml: 1533906435
routes:
  -
    route: robots.txt
    type: staticText
    content: "User-agent: *\r\nDisallow: /typo3/\r\nDisallow: /typo3_src/\r\nAllow: /typo3/sysext/frontend/Resources/Public/*\r\nSitemap: http://devega.local/sitemap.xml?sitemap=pages&cHash=f2d17d236be412917e2d69bff86b5b1e"
websiteTitle: 'deVega Präsentationsmappen'
